### ISSUE TITLE
토론 이슈가 열리면 mattermost로 알림이 가도록 설정하면 좋을 것 같아요!

### ISSUE THREAD

**Issue by minju412** [ssafy-pjt-naem/naem-back#26]
### 📝 Describe

현재 몇 개의 이슈가 올라왔음에도 인지하지 못하고 있었네요..!

이처럼 누락되는 상황을 방지하고 더 빠른 소통을 위해,
`suggestion` label이 달린 이슈가 있을 때, mattermost로 알림이 가도록 설정했습니다!

### 1. Github Actions 워크플로우 설정
```yml
name: GitHub Issue Notification

on:
  issues:
    types: [labeled]

jobs:
  notify_mattermost:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Send notification to MatterMost
        id : send-to-mattermost
        if: github.event.label.name == '🙋‍♂️ suggestion'
        env:
          MATTERMOST_WEBHOOK_URL: ${{ secrets.MATTERMOST_WEBHOOK_URL }}
        run: |
          ISSUE_TITLE=$(curl -sS "${{ github.event.issue.url }}" | jq -r '.title')
          MESSAGE="🙋‍♂️ 새로운 이슈가 열렸어욥!!: $ISSUE_TITLE\n${{ github.event.issue.html_url }}"
          curl -X POST -H "Content-type: application/json" --data "{\"text\":\"$MESSAGE\"}" $MATTERMOST_WEBHOOK_URL
```

🔍 다양한 event trigger와 types를 확인하고 싶다면? [공식 문서](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#discussion﻿)

### 2. MatterMost Incomming Webhooks 설정

1) MatterMost > Channels > 통합 선택
![image](https://github.com/ssafy-pjt-naem/naem-back/assets/59405576/aa6cc218-ca63-4365-a7da-0173af43e8c4)

2) 전체 Incomming Webhook 선택
![image](https://github.com/ssafy-pjt-naem/naem-back/assets/59405576/f324ade2-0205-4d51-acfd-a5ba5e5ead7c)

3) `Incomming Webhook 추가하기` 선택
![image](https://github.com/ssafy-pjt-naem/naem-back/assets/59405576/f9cd9761-3dac-47b0-a8c6-68d6a8adebdc)

이제 생성된 URL을 Github Secrets에 등록하면 됩니다!

### 3. GitHub Secrets 설정
1) GitHub 저장소의 Settings > Secrets and variables > Actions 섹션으로 이동하여 `New Repository Secret`을 클릭한다.

2) Name은 `MATTERMOST_WEBHOOK_URL`로 설정하고, Secret에는 직전에 생성한 URL을 복사/붙여넣는다.
![image](https://github.com/ssafy-pjt-naem/naem-back/assets/59405576/f0c8193c-2918-4ce6-a39f-98d91a8e2f1e)

### 🎉 완료
이제 새로운 이슈가 등록되었을 때 MM으로 알림을 받아볼 수 있습니다! 
![image](https://github.com/ssafy-pjt-naem/naem-back/assets/59405576/7835f5ed-b566-49e0-9fc1-e1f9771a80cb)

 

### ✅ Tasks

github action을 이용해 issue-notification 생성하기

### 🙋🏻 More

하나, 둘, 셋 화이팅
